// Shared disposable/temporary email domain check, used by membership + quickpay signup
// Disposable/temporary email domains to block (comprehensive list)
const DISPOSABLE_EMAIL_DOMAINS = new Set([
    // Common disposable email services
    'tempmail.com', 'temp-mail.org', 'temp-mail.io', 'tempail.com', 'tempr.email',
    'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org', 'guerrillamail.biz',
    'mailinator.com', 'mailinator.net', 'mailinator.org', 'mailinator2.com',
    '10minutemail.com', '10minutemail.net', '10minutemail.org', '10minmail.com',
    'throwaway.email', 'throwawaymail.com', 'throam.com',
    'fakeinbox.com', 'fakemailgenerator.com', 'fakemail.net',
    'trashmail.com', 'trashmail.net', 'trashmail.org', 'trashemail.de',
    'yopmail.com', 'yopmail.fr', 'yopmail.net', 'cool.fr.nf', 'jetable.fr.nf',
    'dispostable.com', 'discard.email', 'discardmail.com', 'discardmail.de',
    'mailcatch.com', 'mailnesia.com', 'mailnull.com',
    'spamgourmet.com', 'spambox.us', 'spamfree24.org', 'spamherelots.com',
    'maildrop.cc', 'mailsac.com', 'mailslurp.com',
    'getnada.com', 'nada.email', 'tempinbox.com', 'tempinbox.co.uk',
    'sharklasers.com', 'spam4.me', 'grr.la', 'guerrillamailblock.com',
    'pokemail.net', 'emailondeck.com', 'anonymmail.net',
    'mintemail.com', 'mytrashmail.com', 'mt2009.com', 'trash2009.com',
    'bugmenot.com', 'bumpymail.com', 'buyusedlibrarybooks.org',
    'despam.it', 'despammed.com', 'devnullmail.com', 'dfgh.net',
    'dodgeit.com', 'dodgit.com', 'dodgit.org', 'dontreg.com', 'dontsendmespam.de',
    'e4ward.com', 'emailias.com', 'emailigo.de', 'emailsensei.com', 'emailtemporario.com.br',
    'emailthe.net', 'emailto.de', 'emailwarden.com', 'emailx.at.hm', 'emailxfer.com',
    'emz.net', 'enterto.com', 'ephemail.net', 'etranquil.com', 'etranquil.net',
    'evopo.com', 'explodemail.com', 'express.net.ua', 'eyepaste.com',
    'fastacura.com', 'fastchevy.com', 'fastchrysler.com', 'fastkawasaki.com', 'fastmazda.com',
    'fastnissan.com', 'fastsubaru.com', 'fastsuzuki.com', 'fasttoyota.com', 'fastyamaha.com',
    'filzmail.com', 'fixmail.tk', 'fizmail.com', 'flyspam.com', 'footard.com',
    'forgetmail.com', 'fr33mail.info', 'frapmail.com', 'friendlymail.co.uk',
    'garliclife.com', 'gehensiull.com', 'get1mail.com', 'get2mail.fr', 'getairmail.com',
    'getmails.eu', 'getonemail.com', 'getonemail.net', 'ghosttexter.de',
    'girlsundertheinfluence.com', 'gishpuppy.com', 'goemailgo.com', 'gorillaswithdirtyarmpits.com',
    'gotmail.com', 'gotmail.net', 'gotmail.org', 'gotti.otherinbox.com',
    'great-host.in', 'greensloth.com', 'gsrv.co.uk', 'guerillamail.biz', 'guerillamail.com',
    'guerillamail.de', 'guerillamail.info', 'guerillamail.net', 'guerillamail.org',
    'gustr.com', 'h8s.org', 'haltospam.com', 'harakirimail.com', 'hatespam.org',
    'herp.in', 'hidemail.de', 'hidzz.com', 'hmamail.com', 'hochsitze.com',
    'hopemail.biz', 'hotpop.com', 'hulapla.de', 'ieatspam.eu', 'ieatspam.info',
    'ieh-mail.de', 'ihateyoualot.info', 'iheartspam.org', 'imails.info', 'imgof.com',
    'imgv.de', 'imstations.com', 'inbax.tk', 'inbox.si', 'inboxalias.com',
    'inboxclean.com', 'inboxclean.org', 'incognitomail.com', 'incognitomail.net',
    'incognitomail.org', 'infocom.zp.ua', 'insorg-mail.info', 'instant-mail.de',
    'ip6.li', 'ipoo.org', 'irish2me.com', 'iwi.net', 'jetable.com', 'jetable.net',
    'jetable.org', 'jnxjn.com', 'jobbikszansen.com', 'jourrapide.com', 'jsrsolutions.com',
    'kasmail.com', 'kaspop.com', 'keepmymail.com', 'killmail.com', 'killmail.net',
    'kimsdisk.com', 'klassmaster.com', 'klassmaster.net', 'klzlv.com', 'kulturbetrieb.info',
    'kurzepost.de', 'lackmail.net', 'lags.us', 'landmail.co', 'lastmail.co',
    'lavabit.com', 'letthemeatspam.com', 'lhsdv.com', 'lifebyfood.com', 'link2mail.net',
    'litedrop.com', 'loadby.us', 'login-email.ml', 'lol.ovpn.to', 'lookugly.com',
    'lopl.co.cc', 'lortemail.dk', 'lovemeleaveme.com', 'lr78.com', 'luckymail.org',
    'maboard.com', 'mail-hierarchie.net', 'mail.by', 'mail.mezimages.net', 'mail.zp.ua',
    'mail114.net', 'mail333.com', 'mail4trash.com', 'mailbidon.com', 'mailblocks.com',
    'mailbucket.org', 'mailcat.biz', 'mailcity.com', 'mailde.de', 'mailde.info',
    'maildrop.cf', 'maildrop.ga', 'maildrop.gq', 'maildrop.ml', 'maildx.com',
    'mailed.ro', 'maileater.com', 'mailexpire.com', 'mailfa.tk', 'mailforspam.com',
    'mailfree.ga', 'mailfreeonline.com', 'mailguard.me', 'mailhazard.com', 'mailhazard.us',
    'mailhz.me', 'mailimate.com', 'mailin8r.com', 'mailinater.com', 'mailincubator.com',
    'mailismagic.com', 'mailjunk.cf', 'mailjunk.ga', 'mailjunk.gq', 'mailjunk.ml',
    'mailjunk.tk', 'mailmate.com', 'mailme.gq', 'mailme.ir', 'mailme.lv', 'mailme24.com',
    'mailmetrash.com', 'mailmoat.com', 'mailnator.com', 'mailnull.com', 'mailorg.org',
    'mailpick.biz', 'mailquack.com', 'mailrock.biz', 'mailseal.de', 'mailshell.com',
    'mailsiphon.com', 'mailslapping.com', 'mailspam.xyz', 'mailtemp.info', 'mailtothis.com',
    'mailzilla.com', 'mailzilla.org', 'makemetheking.com', 'manifestgenerator.com',
    'manybrain.com', 'mbx.cc', 'mega.zik.dj', 'meinspamschutz.de', 'meltmail.com',
    'messagebeamer.de', 'mezimages.net', 'mierdamail.com', 'migmail.pl', 'migumail.com',
    'ministry-of-silly-walks.de', 'mintemail.com', 'misterpinball.de', 'mmmmail.com',
    'moakt.com', 'mobi.web.id', 'mobileninja.co.uk', 'moburl.com', 'mohmal.com',
    'moncourrier.fr.nf', 'monemail.fr.nf', 'monmail.fr.nf', 'monumentmail.com',
    'ms9.mailslite.com', 'msa.minsmail.com', 'msb.minsmail.com', 'msg.mailslite.com',
    'mxfuel.com', 'my10minutemail.com', 'mycleaninbox.net', 'myemailboxy.com',
    'mymail-in.net', 'mymailoasis.com', 'mynetstore.de', 'mypacks.net', 'mypartyclip.de',
    'myphantomemail.com', 'myspaceinc.com', 'myspaceinc.net', 'myspacepimpedup.com',
    'myspamless.com', 'mytempemail.com', 'mytempmail.com', 'mytrashmail.com',
    'nabuma.com', 'neomailbox.com', 'nervmich.net', 'nervtmansen.com', 'netmails.com',
    'netmails.net', 'netzidiot.de', 'neverbox.com', 'nice-4u.com', 'nincsmail.hu',
    'nmail.cf', 'nobulk.com', 'noclickemail.com', 'nogmailspam.info', 'nomail.pw',
    'nomail.xl.cx', 'nomail2me.com', 'nomorespamemails.com', 'nospam.ze.tc', 'nospam4.us',
    'nospamfor.us', 'nospammail.net', 'nospamthanks.info', 'notmailinator.com',
    'notsharingmy.info', 'nowhere.org', 'nowmymail.com', 'ntlhelp.net', 'nurfuerspam.de',
    'nus.edu.sg', 'nwldx.com', 'objectmail.com', 'obobbo.com', 'odnorazovoe.ru',
    'oneoffemail.com', 'onewaymail.com', 'online.ms', 'oopi.org', 'opayq.com',
    'ordinaryamerican.net', 'otherinbox.com', 'ourklips.com', 'outlawspam.com',
    'ovpn.to', 'owlpic.com', 'pancakemail.com', 'pimpedupmyspace.com', 'pjjkp.com',
    'plexolan.de', 'poczta.onet.pl', 'politikerclub.de', 'poofy.org', 'pookmail.com',
    'pop3.xyz', 'proxymail.eu', 'prtnx.com', 'punkass.com', 'putthisinyourspamdatabase.com',
    'pwrby.com', 'q314.net', 'qisdo.com', 'qisoa.com', 'quickinbox.com',
    'quickmail.nl', 'rainmail.biz', 'rcpt.at', 're-gister.com', 'reallymymail.com',
    'realtyalerts.ca', 'receiveee.chickenkiller.com', 'receiveee.com', 'recode.me',
    'recursor.net', 'recyclemail.dk', 'regbypass.com', 'regbypass.comsafe-mail.net',
    'rejectmail.com', 'remail.cf', 'remail.ga', 'rhyta.com', 'rklips.com',
    'rmqkr.net', 'rppkn.com', 'rtrtr.com', 's0ny.net', 'safe-mail.net',
    'safersignup.de', 'safetymail.info', 'safetypost.de', 'sandelf.de', 'saynotospams.com',
    'selfdestructingmail.com', 'sendspamhere.com', 'sharklasers.com', 'shieldemail.com',
    'shiftmail.com', 'shitmail.me', 'shortmail.net', 'showslow.de', 'sibmail.com',
    'sinnlos-mail.de', 'siteposter.net', 'skeefmail.com', 'slaskpost.se', 'slave-auctions.net',
    'slopsbox.com', 'slowslow.de', 'smap.4nmv.ru', 'smashmail.de', 'smellfear.com',
    'snakemail.com', 'sneakemail.com', 'snkmail.com', 'sofimail.com', 'sofort-mail.de',
    'sogetthis.com', 'solvemail.info', 'soodomail.com', 'soodonims.com', 'spam.la',
    'spam.su', 'spam4.me', 'spamavert.com', 'spambob.com', 'spambob.net', 'spambob.org',
    'spambog.com', 'spambog.de', 'spambog.net', 'spambog.ru', 'spambox.info',
    'spambox.irishspringrealty.com', 'spambox.us', 'spamcannon.com', 'spamcannon.net',
    'spamcero.com', 'spamcon.org', 'spamcorptastic.com', 'spamcowboy.com', 'spamcowboy.net',
    'spamcowboy.org', 'spamday.com', 'spameater.com', 'spameater.org', 'spamex.com',
    'spamfree.eu', 'spamfree24.com', 'spamfree24.de', 'spamfree24.eu', 'spamfree24.info',
    'spamfree24.net', 'spamfree24.org', 'spamgoes.in', 'spamherelots.com', 'spamhereplease.com',
    'spamhole.com', 'spamify.com', 'spaminator.de', 'spamkill.info', 'spaml.com',
    'spaml.de', 'spamlot.net', 'spammotel.com', 'spamobox.com', 'spamoff.de',
    'spamsalad.in', 'spamslicer.com', 'spamspot.com', 'spamstack.net', 'spamthis.co.uk',
    'spamtroll.net', 'speed.1s.fr', 'spoofmail.de', 'squizzy.de', 'ssoia.com',
    'startkeys.com', 'stinkefinger.net', 'stop-my-spam.cf', 'stop-my-spam.com',
    'stop-my-spam.ga', 'stop-my-spam.ml', 'stop-my-spam.tk', 'streetwisemail.com',
    'stuffmail.de', 'super-auswahl.de', 'supergreatmail.com', 'supermailer.jp',
    'superrito.com', 'superstachel.de', 'suremail.info', 'svk.jp', 'sweetxxx.de',
    'tafmail.com', 'tagyourself.com', 'talkinator.com', 'tapchicuoihoi.com',
    'techemail.com', 'techgroup.me', 'teewars.org', 'teleosaurs.xyz', 'teleworm.com',
    'teleworm.us', 'temp.emeraldwebmail.com', 'temp15qm.com', 'tempail.com',
    'tempalias.com', 'tempe-mail.com', 'tempemail.biz', 'tempemail.co.za', 'tempemail.com',
    'tempemail.net', 'tempinbox.co.uk', 'tempinbox.com', 'tempmail.co', 'tempmail.de',
    'tempmail.eu', 'tempmail.it', 'tempmail.net', 'tempmail.us', 'tempmail2.com',
    'tempmaildemo.com', 'tempmailer.com', 'tempmailer.de', 'tempomail.fr', 'temporarily.de',
    'temporarioemail.com.br', 'temporaryemail.net', 'temporaryemail.us', 'temporaryforwarding.com',
    'temporaryinbox.com', 'temporarymailaddress.com', 'tempthe.net', 'thankspam.net',
    'thankyou2010.com', 'thecloudindex.com', 'thelimestones.com', 'thisisnotmyrealemail.com',
    'throam.com', 'throwam.com', 'throwawayemailaddress.com', 'throwawaymail.com',
    'tilien.com', 'tittbit.in', 'tmailinator.com', 'toiea.com', 'toomail.biz',
    'tradermail.info', 'trash-amil.com', 'trash-mail.at', 'trash-mail.com', 'trash-mail.de',
    'trash-mail.ga', 'trash-mail.gq', 'trash-mail.ml', 'trash-mail.tk', 'trash2009.com',
    'trash2010.com', 'trash2011.com', 'trashcanmail.com', 'trashdevil.com', 'trashdevil.de',
    'trashemail.de', 'trashmail.at', 'trashmail.com', 'trashmail.de', 'trashmail.me',
    'trashmail.net', 'trashmail.org', 'trashmail.ws', 'trashmailer.com', 'trashymail.com',
    'trashymail.net', 'trbvm.com', 'trickmail.net', 'trillianpro.com', 'tryalert.com',
    'turual.com', 'twinmail.de', 'twoweirdtricks.com', 'tyldd.com', 'uggsrock.com',
    'umail.net', 'upliftnow.com', 'uplipht.com', 'uroid.com', 'us.af', 'valemail.net',
    'venompen.com', 'veryrealemail.com', 'viditag.com', 'viralplays.com', 'vkcode.ru',
    'vomoto.com', 'vpn.st', 'vsimcard.com', 'vubby.com', 'walala.org', 'walkmail.net',
    'webemail.me', 'webm4il.info', 'webuser.in', 'wee.my', 'weg-werf-email.de',
    'wegwerf-email-addressen.de', 'wegwerf-emails.de', 'wegwerfadresse.de', 'wegwerfemail.com',
    'wegwerfemail.de', 'wegwerfmail.de', 'wegwerfmail.info', 'wegwerfmail.net', 'wegwerfmail.org',
    'wetrainbayarea.com', 'wetrainbayarea.org', 'wh4f.org', 'whatiaas.com', 'whatpaas.com',
    'whopy.com', 'whtjddn.33mail.com', 'whyspam.me', 'wilemail.com', 'willhackforfood.biz',
    'willselfdestruct.com', 'winemaven.info', 'wolfsmail.tk', 'wollan.info', 'worldspace.link',
    'wronghead.com', 'wuzup.net', 'wuzupmail.net', 'wwwnew.eu', 'x.ip6.li',
    'xagloo.com', 'xemaps.com', 'xents.com', 'xmaily.com', 'xoxy.net', 'yapped.net',
    'yeah.net', 'yep.it', 'yogamaven.com', 'yopmail.com', 'yopmail.fr', 'yopmail.gq',
    'yopmail.net', 'you-spam.com', 'yourdomain.com', 'ypmail.webarnak.fr.eu.org',
    'yuurok.com', 'zehnminuten.de', 'zehnminutenmail.de', 'zetmail.com', 'zippymail.info',
    'zoaxe.com', 'zoemail.com', 'zoemail.net', 'zoemail.org', 'zomg.info', 'zxcv.com',
    'zxcvbnm.com', 'zzz.com'
]);

// Check if email domain is disposable
function isDisposableEmail(email) {
    const domain = email.split('@')[1]?.toLowerCase();
    if (!domain) return true;
    return DISPOSABLE_EMAIL_DOMAINS.has(domain);
}

module.exports = { DISPOSABLE_EMAIL_DOMAINS, isDisposableEmail };
